server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  swagger:
    package: com.hmall.cart.controller
    title: "黑马商城购物车服务API"
    description: "黑马商城购物车服务接口文档"
  db:
    database: hm-cart